### ISSUE TITLE
chillup support

### ISSUE THREAD

**Issue by Cokemonkey11** [HerlySQR/Unit-Transmission#1]
```
$ chillup --index

To make your own wurst library searchable, it must be:

-   Uploaded to GitHub in a public repository
-   Tagged with the `wurst` and `dependency` topics
```

**Comment by HerlySQR** [comment]
I'm still very noob in Git, so I searched and it can be done doing
`git push main <tagname>`
Or creating a release, is that correct?

**Comment by HerlySQR** [comment]
> ```
> $ chillup --index
> 
> To make your own wurst library searchable, it must be:
> 
> -   Uploaded to GitHub in a public repository
> -   Tagged with the `wurst` and `dependency` topics
> ```

Did github notify the replies or I have to directly reply to github actually notify?, because I didn't get a notification of this issue, I had to casually look here.

**Comment by Cokemonkey11** [comment]
You can control notifications with this
![image](https://user-images.githubusercontent.com/1418966/167735849-2e56d302-2f7f-4154-a464-68fd6d3848d0.png)

> git push main <tagname>
> Or creating a release, is that correct?

For chillup this is not needed. Wurst just downloads from git - there is no versioning system

> Tagged with the `wurst` and `dependency` topics

It's talking about this:

![image](https://user-images.githubusercontent.com/1418966/167736553-7711e877-b17c-4fec-9730-0e8fc65fddcc.png)

**Comment by HerlySQR** [comment]
> It's talking about this:
> 
> ![image](https://user-images.githubusercontent.com/1418966/167736553-7711e877-b17c-4fec-9730-0e8fc65fddcc.png)

Ok, got it, thanks.

> You can control notifications with this ![image](https://user-images.githubusercontent.com/1418966/167735849-2e56d302-2f7f-4154-a464-68fd6d3848d0.png)

The weird thing is I had set it in All Activity
![image](https://user-images.githubusercontent.com/87576302/167738823-2d187959-fa4f-49e9-b917-d069b8199dee.png)

**Comment by Cokemonkey11** [comment]
```
$ chillup --dump | grep Transmis
https://github.com/HerlySQR/Unit-Transmission                       (No description)
```

It's working
